### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [jakecdoyle/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by jakecdoyle** [comment]
I noticed this last night and was going to ask someone, so I'm glad you've addressed it. It looks like I've fixed it, though. I added <meta name="viewport" content="width=device-width, initial-scale=1"> to my <head>.

**Comment by kenmazaika** [comment]
Thumbs up on getting the viewport meta tag.  :+1:
